baseURL: https://pedrofigueiroa.netlify.app/
title: Meu primeiro Site em R
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: Sobre Mim
      name: Sobre Mim
      url: /about/
      weight: 3
params:
  author: Pedro Figueiroa
  description: Meu primeiro site em R.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/pedrofigueiroa
    - icon: twitter
      name: Twitter
      url: https://twitter.com/_frances_23
